#include "ShaderManager.hpp"

#include <cassert>

// Include the autogenerated headers only in the implementation file
#include "build/_autogen/miss.slang.h"
#include "build/_autogen/raygen.slang.h"

/**********************************************************/
ShaderManager::ShaderManager()
/**********************************************************/
{
  // Initialize defaults
  m_raygen = {
      .filename = "raygen.slang",
      .entryPoint = "rgenMain",
      .spirv = raygen_slang,
  };

  m_miss = {
      .filename = "miss.slang",
      .entryPoint = "rmissMain",
      .spirv = miss_slang,
  };
}

/**********************************************************/
void ShaderManager::registerMaterial(MaterialType type,
                                     const std::string& baseName,
                                     std::span<const uint32_t> spirv)
/**********************************************************/
{
  assert(m_registry.find(type) == m_registry.end() &&
         "MaterialType already registered!");

  m_registry[type] = MaterialEntry{.type = type,
                                   .filename = baseName + ".slang",
                                   .entryPoint = "rchit_" + baseName,
                                   .sbtIndex = 0,
                                   .spirv = spirv};
}

/**********************************************************/
uint32_t ShaderManager::getSbtOffset(MaterialType type) const
/**********************************************************/
{
  auto it = m_registry.find(type);
  return (it != m_registry.end()) ? it->second.sbtIndex : 0;
}

/**********************************************************/
std::map<MaterialType, MaterialEntry>& ShaderManager::getRegistry()
/**********************************************************/
{
  return m_registry;
}

/**********************************************************/
const std::map<MaterialType, MaterialEntry>& ShaderManager::getRegistry() const
/**********************************************************/
{
  return m_registry;
}

/**********************************************************/
const RaygenEntry& ShaderManager::getRaygen() const
/**********************************************************/
{
  return m_raygen;
}

/**********************************************************/
const MissEntry& ShaderManager::getMiss() const
/**********************************************************/
{
  return m_miss;
}
