#include "shader_manager.hpp"

#include <cassert>

#include "core/string_utils.hpp"

// Include the autogenerated headers only in the implementation file

#ifdef __linux__
#include "_autogen/miss.slang.h"
#include "_autogen/raygen.slang.h"
#include "_autogen/shadow.miss.slang.h"
#endif

/**********************************************************/
ShaderManager::ShaderManager()
/**********************************************************/
{

#ifdef __linux__
  // Initialize defaults
  m_raygen = {
      .prettyName = "Raygen",
      .filename = "raygen.slang",
      .entryPoint = "rgenMain",
      .spirv = raygen_slang,
  };

  m_miss = {
      .prettyName = "Miss",
      .filename = "miss.slang",
      .entryPoint = "rmissMain",
      .spirv = miss_slang,
  };

  m_shadowMiss = {
      .prettyName = "Shadow miss",
      .filename = "shadow.miss.slang",
      .entryPoint = "main",
      .spirv = shadow_miss_slang,
  };
#endif
}

/**********************************************************/
void ShaderManager::registerMaterial(MaterialType type,
                                     const std::string& baseName,
                                     std::span<const uint32_t> spirv)
/**********************************************************/
{
  assert(m_registry.find(type) == m_registry.end() &&
         "MaterialType already registered!");

  m_registry[type] = MaterialEntry{.type = type,
                                   .prettyName = core::capitalize(baseName),
                                   .filename = baseName + ".slang",
                                   .entryPoint = "rchit_" + baseName,
                                   .sbtIndex = 0,
                                   .spirv = spirv};
}

/**********************************************************/
uint32_t ShaderManager::getSbtOffset(MaterialType type) const
/**********************************************************/
{
  auto it = m_registry.find(type);
  return (it != m_registry.end()) ? it->second.sbtIndex : 0;
}

/**********************************************************/
std::map<MaterialType, MaterialEntry>& ShaderManager::getRegistry()
/**********************************************************/
{
  return m_registry;
}

/**********************************************************/
const std::map<MaterialType, MaterialEntry>& ShaderManager::getRegistry() const
/**********************************************************/
{
  return m_registry;
}

/**********************************************************/
const RaygenEntry& ShaderManager::getRaygen() const
/**********************************************************/
{
  return m_raygen;
}

/**********************************************************/
const MissEntry& ShaderManager::getMiss() const
/**********************************************************/
{
  return m_miss;
}

/**********************************************************/
const MissEntry& ShaderManager::getShadowMiss() const
/**********************************************************/
{
  return m_shadowMiss;
}
